kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: catzclaim
 labels:
  app: hello-catz
spec:
 accessModes:
  - ReadOnlyMany
 resources:
  requests:
   storage: 1Gi
 storageClassName: slow
 selector:
  name: catz
